version: '3.8'
services:
    redis-db:
        image: 'redis'
        ports:
            - '6379:6379'

    rabbitmq:
        image: 'rabbitmq:3-management'
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            hostname: "rabbitmq"

    category-svc:
        build:
            context: './'
            dockerfile: 'apps/svc/category-svc/Dockerfile-dev'
        volumes:
            - ./:/app
        ports:
            - "4111:4101"
        healthcheck:
            test: curl --fail http://localhost:4000/health-check || exit 1
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 10s
        environment:
            PORT: 4000

    web-api:
        build:
            context: './'
            dockerfile: './apps/api/Dockerfile-dev'
        volumes:
            - ./:/app
        ports:
            - '3333:3333'
        environment:
            PORT: 3333
        depends_on:
            - category-svc
