version: '3.8'
services:
    redis-db:
        image: 'redis'
        ports:
            - '6379:6379'

    rabbitmq:
        image: 'rabbitmq:3-management'
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            hostname: "rabbitmq"

    category-svc:
        build:
            context: './'
            dockerfile: 'apps/svc/category-svc/Dockerfile-dev'
        volumes:
            - ./:/app
        ports:
            - "4111:4101"
        healthcheck:
            test: curl --fail http://localhost:4000/health-check || exit 1
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 10s
        environment:
            PORT: 4000

    web-api:
        build:
            context: './'
            dockerfile: './apps/api/Dockerfile-dev'
        volumes:
            - ./:/app
        ports:
            - '3333:3333'
        environment:
            PORT: 3333
        depends_on:
            - category-svc

    # articles-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/articles-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     network_mode: host
    #     depends_on:
    #         - redis-db
    #         - rabbitmq
#             email-svc
        # environment:
            # PORT: 4000
            # DB_HOST: host.docker.internal
            # DB_PORT: '5432'
            # DB_USERNAME: 'postgres'
            # DB_PASSWORD: '1lOh301SKogV'
            # DB_DATABASE: '77_dev'
            # REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
            # RMQ_URL: 'amqp://rabbitmq:5672'
            # ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
            # GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # comments-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/comments-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # email-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/email-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         EMAIL: 'seventy.seven.service@gmail.com'
    #         EMAIL_PASSWORD: 'RPf8OWGQ%CcrrAdj5PxX'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # facebook-posts-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/facebook-posts-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         FACEBOOK_CRAWL_API_URL: 'https://sausainis.eu/api/ProfileScrapper/GetPosts'
    #     depends_on:
    #         - posts-svc

    # featured-profiles-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/featured-profiles-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #     depends_on:
    #         - profiles-svc

    # feed-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/feed-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'
    #     depends_on:
    #         - articles-svc
    #         - posts-svc
    #         - comments-svc

    # images-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/images-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         IMAGES_BUCKET: 'seventy-seven-dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # likes-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/likes-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # posts-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/posts-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # profiles-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/profiles-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # search-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/search-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # shares-svc:
    #     build:
    #         context: './'
    #         dockerfile: 'apps/svc/shares-svc/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     environment:
    #         PORT: 4000
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'

    # web-api:
    #     build:
    #         context: './'
    #         dockerfile: './apps/apis/web-api/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     ports:
    #         - '3333:3333'
    #     environment:
    #         PORT: 3333
    #         SECRET_KEY: 'A56CBF2175DF7A1497475A7911C26'
    #         HTTP_BASIC_USER: '77'
    #         HTTP_BASIC_PASS: 'seventyseven123!.'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'
    #     depends_on:
    #         - account-svc
    #         - articles-svc
    #         - articles-importer-svc
    #         - comments-svc
    #         - feed-svc
    #         - images-svc
    #         - likes-svc
    #         - posts-svc
    #         - profiles-svc
    #         - search-svc
    #         - shares-svc

    # messages-api:
    #     build:
    #         context: './'
    #         dockerfile: './apps/apis/messages-api/Dockerfile-dev'
    #     volumes:
    #         - ./:/app
    #     ports:
    #         - '4101:4000'
    #     environment:
    #         PORT: 4000
    #         SECRET_KEY: 'A56CBF2175DF7A1497475A7911C26'
    #         DB_HOST: '34.83.104.106'
    #         DB_PORT: '5432'
    #         DB_USERNAME: 'postgres'
    #         DB_PASSWORD: '1lOh301SKogV'
    #         DB_DATABASE: '77_dev'
    #         REDIS_URL: 'redis://redis-db:6379?defaultDatabase=0'
    #         RMQ_URL: 'amqp://rabbitmq:5672'
    #         ACCOUNT_RMQ_URL: "amqp://rabbitmq:5672"
    #         GOOGLE_APPLICATION_CREDENTIALS: './keys/seventy-seven-336018-api-dev.json'
    #     depends_on:
    #         - profiles-svc
